### ISSUE TITLE
Update examples to use RTIC V2

### ISSUE THREAD

**Issue by snorkman88** [pdh11/cotton#6]
Hi there, first of all great project.  Are you planning to migrate the examples in `/cross` directory to RTIC V2?
I would like to try this on an STM32F411.

**Comment by pdh11** [comment]
At some point yes! it's a bit annoying because you can't have both RTIC 1 and RTIC 2 in the same crate, even if each individual "bin" only links against one or the other. But I could easily make a new crate for (say) stm32f746-nucleo-rtic2, and for that matter stm32f746-nucleo-embassy. I'll look into it...

**Comment by snorkman88** [comment]
Does it actually make sense to keep RTIC V1?

**Comment by pdh11** [comment]
There's some new, RTIC-2-based, examples now if you take a look. They use the newest cotton-ssdp 0.0.4, and there have been some breaking changes since 0.0.3 (if you're using the low-level `Engine` struct). Writing them provoked and helped me fix a long-standing bug with SSDP timeouts, so thanks!

It makes sense to keep the RTIC-1 examples because I need to guard against future crate releases breaking RTIC-1 support. (And porting to RTIC-2 isn't entirely straightforward, so I'm not sure that all current RTIC-1 projects will do so.)

**Comment by snorkman88** [comment]
Hey thanks a lot! I will try them as soon as I have some time.
